### ISSUE TITLE
Add Eric Smalling as "Reviewer" for vuln-mgmt sub-directory

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#109]
Pre-requisite: Eric needs to be an Org member for Kubernetes: https://github.com/kubernetes/org/issues/4641

- Duplicate OWNERS file in sig-security-tooling folder into both the sub-directories 
- Update the reviewers list to add  Eric Smalling in it for: https://github.com/kubernetes/sig-security/tree/main/sig-security-tooling/vulnerability-mgmt. 

**Context**: Eric has successfully shadowed me in maintaining the vulnerability scanning for last several months. So we want to add him as a reviewer as a recognition of his work and effort.

**Comment by ericsmalling** [comment]
@PushkarJ Should I be a reviewer for `cve-feed` too or just `vulnerability-mgmt`?

**Comment by PushkarJ** [comment]
Let's go with `vulnerability-mgmt` only for now ?
