### ISSUE TITLE
Build a Project Board

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#11]
**What?**

Could be as simple as Todo, In-progress and Done

**How?**
Actually do not have a good idea, but somebody has done this before for a small, medium or large project, would love to see them pick this up. 

One good example: https://github.com/kubernetes/website/projects/11

**Why?**

To have co-chairs and sub-project leads + contributors to have one place to find out what is going on in sig-security

/kind design
/sig security
/help
/good-first-issue

**Comment by ShivamTyagi12345** [comment]
> Thank you @ShivamTyagi12345 for pointing me to the right resources. I did not realize that project boards needed org. membership. Inspired from your project board, I created this tracker for now: https://github.com/orgs/kubernetes/projects/64
> 
> On a related note, when you think you are eligible to become org member for k8s as per these guidelines: https://github.com/kubernetes/community/blob/master/community-membership.md, I will be happy to be one of your sponsors!!

I have applied for a membership @PushkarJ .Thank you for your support

**Comment by PushkarJ** [comment]
Closing this now, after review of the board in the SIG Security meeting, which was received well. Also, confirmed with Github Admins that this board can not be added to `Projects` tab in the `k/sig-security` repo as that is not possible for Org. Level boards and K8s Org discourages use of repo level boards. 

Thank you for your help on this @ShivamTyagi12345
