### ISSUE TITLE
Housekeeping: archive old meeting notes into git

### ISSUE THREAD

**Issue by tabbysable** [kubernetes/sig-security#120]
to help keep the google docs snappy, let's copy some of the old notes into documents here in this git repo.

Proposed plan:
* Keep the current year and the previous calendar year in the Google doc
* For each year older than that, copy all the meeting notes into a markdown doc for that year
* Get them committed and merged
* Once they are committed and merged, delete them from the tail of the Google doc

**Comment by tabbysable** [comment]
offhand thought: perhaps in a `meeting-notes-archive` directory, with subdirectories per subproject, and then names like `2022.md`?

**Comment by PushkarJ** [comment]
Maybe this was discussed already:

Would this mean our notes are open for whole internet v/s accessible as before to only k-dev mailing list members? If yes, are we all okay with that?

**Comment by tturquette** [comment]
Hello @tabbysable. I am open to help with this activity. Please let me know if this is something I can work on.

**Comment by lavishpal** [comment]
Hi @tabbysable , would like to work on this issue. Can you assign this to me ?

**Comment by tabbysable** [comment]
> Maybe this was discussed already:
> 
> Would this mean our archived notes are open for whole internet v/s accessible as before to only k-dev mailing list members? If yes, are we all okay with that?

Yeah, the notes docs are open for anonymous writes, so it will be good for the archived notes to be open too.

**Comment by tabbysable** [comment]
The three meeting notes docs that would benefit from archiving into git markdown are here:
[SIG Security meeting](https://docs.google.com/document/d/1GgmmNYN88IZ2v2NBiO3gdU8Riomm0upge_XNVxEYXp0/edit)
[Tooling subproject](https://docs.google.com/document/d/1_Rn7S8UPMtXdu6EDl4_L2Ogb433z7hlxPs7El8TfNNg/edit#heading=h.cd9xm2lbvnw4)
[Docs subproject](https://docs.google.com/document/d/11LZn7qWB0OzbpF8va_YYGQE4fuRARCGY9KL87hwBLBI/edit#heading=h.8wbpwik2g82i)

@tturquette @lavishpal Thank you both for your offers to help! You could certainly work together if you liked.

Last time I tried something like this, there were a few ways to copy out of google docs into Markdown with retained formatting, but none of them were perfect. I recommend doing some searching to see if anyone has published a good script or tool for that, and then just giving a try to generate some Markdown from the old notes.

**Comment by tabbysable** [comment]
Please do not delete any of the old notes from the Google docs. I will do that once we have some good markdown files commited to git.
