### ISSUE TITLE
Request to add PR template along with proper README.md

### ISSUE THREAD

**Issue by chetak123** [kubernetes/sig-security#14]
Hey @PushkarJ I saw that this repository is new and soon it will be populated with directory structure https://github.com/kubernetes/sig-security/issues/9. I would like to add proper Repository README.md and PR template (.github) for better contribution. 

Any advice for README.md or addition of any other things would be really helpful.

**Comment by PushkarJ** [comment]
@chetak123 , take a look at issue description for #20 from @savitharaghunathan . It has some good ideas about what to put in the README
