### ISSUE TITLE
Update README.md with sig-security information

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/sig-security#20]
Mirror README.md from - https://github.com/kubernetes/community/tree/master/sig-security

/good-first-issue

**Comment by PushkarJ** [comment]
@savitharaghunathan maybe there is an opportunity to combine this with this one: https://github.com/kubernetes/sig-security/issues/14

**Comment by savitharaghunathan** [comment]
Ha thanks. I will mark this as a duplicate and close it.

**Comment by savitharaghunathan** [comment]
Duplicate issue. See #14. 
/close
