### ISSUE TITLE
REQUEST: Security Assessment for vsphere-csi-driver

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/sig-security#21]
**Is this a Kubernetes sub-project?** 

Yes

**Please tell us a bit about your sub-project** 

vSphere CSI driver is a volume plug-in that runs in a native Kubernetes cluster deployed in vSphere and is responsible for provisioning persistent volumes on vSphere storage.
Repo: https://github.com/kubernetes-sigs/vsphere-csi-driver

**Do you have a preferred timeline for completing the security assessment?**
  

**Please share any additional or alternate points of contact for this request**
@divyenpatel 

cc @PushkarJ

**Comment by PushkarJ** [comment]
/remove-lifecycle stale

@[aladewberry](https://github.com/aladewberry) this is the next project we could tackle for security self-assessment :)

**Comment by PushkarJ** [comment]
/assign aladewberry

(Since you have already started to plan on how to proceed on this. Just assigning this to you for posterity)

**Comment by aladewberry** [comment]
Quick update - I have a meeting scheduled with @xing-yang next week to get connected and figure out where to start.

**Comment by aladewberry** [comment]
> @aladewberry happy to sherpa again. just post meeting/slack info here. thanks!

Thank you! I'm still getting up to speed and will reach out when we starting taking steps!

**Comment by xing-yang** [comment]
This work in on-going.
