### ISSUE TITLE
Docs for scanning known vulnerabilities in container images

### ISSUE THREAD

**Issue by nehaLohia27** [kubernetes/sig-security#25]
Creating this issue to document the periodic scanning process for container images . Please refer to this PR for the work done. https://github.com/kubernetes/test-infra/pull/23419
 
Umbrella issue : https://github.com/kubernetes/sig-security/issues/3

There is a similar doc created for build time dependencies also . Reference PR: https://github.com/kubernetes/sig-security/pull/16

**Comment by jan0ski** [comment]
I'd be happy to take this on!

**Comment by PushkarJ** [comment]
/assign @jan0ski 

yay, thank you Tommy for taking this on :-)

**Comment by savitharaghunathan** [comment]
@PushkarJ do we have a label for tooling?

**Comment by PushkarJ** [comment]
@savitharaghunathan: Nope I have just added sig security label for all the tooling work so far.

**Comment by PushkarJ** [comment]
https://github.com/kubernetes/sig-security/pull/26 is now merged that addresses this issue.

/close
