### ISSUE TITLE
Configure a Prow Job that creates a k/website PR

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#32]
# What

 This issue describes how to achieve that by creating a prow job that automates PR creation to k/website when a new CVE is announced 

# Why 

As part of #1 , we need an automation to update `k/website` page that will host the list of known CVEs.

We will be borrowing heavily from prow [autobumper tool](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/generic-autobumper)

# How
The flow will look something like this:
- Prow job creates JSON blob based on the information found using github label `/official-cve-feed`
- It compares the new generated JSON blob with existing JSON blob on `k/website` page
- Possible location to host the JSON blob: [examples/security](https://github.com/kubernetes/website/tree/main/content/en/examples/security))
- If generated JSON blob is different, than existing JSON blob (including blob does not exist), a new PR is created to update that JSON blob
- Example Prow job could be something like this: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L604-L677
- Skip-Review label and on-call options in the example job are worth exploring to reduce / bypass approver and reviewer availability

# Open items

- Explore the [autobumper tool](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/generic-autobumper) and come up with a shell script or simple go program that will submit a PR via this mechanism
- `skip-review` is only used supported for `kubernetes/test-infra` repo. Check if it would make sense to add this label to `k/website` as well OR move JSON doc under `kubernetes/test-infra`

# Discussion
Slack thread: https://kubernetes.slack.com/archives/C01CUSVMHPY/p1642720739011300

/sig security testing

**Comment by nehaLohia27** [comment]
@PushkarJ  Had a call with @rajaskakodkar to discuss on prow job and pr-creator..If we use pr-creator only , this should be good enough. No need of autobumper tool as it is used mostly for bumping the images. There are 2 main tasks 
1.  To create the wrapper script similar to: https://github.com/kubernetes/test-infra/blob/60549d3fa734ca0881514a2b764c4ac7f978a9f3/hack/autodeps.sh#L58. . this will call our shell/python/golang script to generate json blob and also it will create a PR on website repo. We need to decide on the location to keep this script , should we use the same hack folder in test-infra or something else ? 
2. To create the prowjob yaml file similar to : https://github.com/kubernetes/test-infra/blob/30b07d16e76673365214ac3110080276b512b466/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L542. Can you confirm the location for our prowjob yaml also ? Can we use the same snyk prowjob yaml  or create new one? 
Also we can use same k8s-ci-robot github token to generate PR on website as what rajas mentioned. But needs to be confirmed once. 

Next thing is to ask sig-testing to generate the fork of website repo using k8s-ci-robot. Eg:If we browse this url https://github.com/k8s-ci-robot/website is not working but this url https://github.com/k8s-ci-robot/test-infra works.

**Comment by PushkarJ** [comment]
Awesome progress!! Thank you @rajaskakodkar for your time!!

For 1, yes hack directory seems fine. We can refactor to some other place if folks have feedback during PR time.
For 2, yes a new section of yaml that defines this as a separate job, in the existing [file](https://github.com/kubernetes/test-infra/blob/223540760a567bf26de4673045e6321d37dbe554/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-security-trusted.yaml) seems fine. Check the example from RelEng [here]( https://github.com/kubernetes/test-infra/blob/223540760a567bf26de4673045e6321d37dbe554/config/jobs/kubernetes/sig-k8s-infra/trusted/releng/releng-trusted.yaml#L54 ) of how they have three jobs defined 

For forking k/website started a [thread](https://kubernetes.slack.com/archives/C09QZ4DQB/p1645129435563709) on slack to figure out a way to request it

**Comment by nehaLohia27** [comment]
Thanks @PushkarJ for the info.
In the existing prow job yaml https://github.com/kubernetes/test-infra/blob/223540760a567bf26de4673045e6321d37dbe554/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-security-trusted.yaml#L87 
I think we need to change the dashboard name . Any other data change required ?

**Comment by PushkarJ** [comment]
@sftim We need to externally trigger the build and also use GCS bucket. 

Basically, Pull from GCS bucket and then generate the JSON file dynamically when we trigger the website build. Here's the relevant KEP [section](https://github.com/kubernetes/enhancements/pull/3204/files#diff-ed5b769a7ca6a409326fbdfa8bc2293f14300a5db1ad41a2dfe4c3d233797c24R271-R287)

**Comment by nehaLohia27** [comment]
@PushkarJ I think we can close this issue as seems duplicate of #39. So that we can update issue #39 with the latest information.

**Comment by PushkarJ** [comment]
/close 

(in favor of #39)
