### ISSUE TITLE
Configure a prow job that writes CVE JSON data to GC bucket every hour

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#33]
# What

Create a Prow job that runs a Github query to create a JSON blob of CVE data and writes it to a GCB bucket

# Why

We need a way where Hugo can fetch always the latest data about officially announced CVEs. Google Cloud bucket seems like a simpler way to host that data

# How

- Example script that writes to GCB can be found [here](https://github.com/kubernetes/test-infra/blob/8bddea4df208ea536b18e5eed7edb2328148f7e6/triage/update_summaries.sh#L99-L103)
- Example prow job that uses this script to write to a GCB bucket is [here](https://github.com/kubernetes/test-infra/blob/6dec48b89caab69806c17f72dd32d88ba1b1dcc0/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-k8s-infra-test-infra.yaml#L84-L114)
- Overall docs for writing to bucket can be found [here](https://cloud.google.com/storage/docs/quickstart-gsutil#upload_an_object_into_your_bucket)

## Pre-requisites

- Need to request a bucket for which following information is needed. Example Issue: https://github.com/kubernetes/k8s.io/pull/2570
- Google Group of Humans who will own this infra: https://github.com/kubernetes/k8s.io/blob/main/groups/sig-security/groups.yaml (Group description might need an update)
- Name of the bucket: `k8s-cve-feed` 
- Service account name: `k8s-cve-feed` 
Note: The names here are suggestions, final naming convention is up to SIG k8s Infra

## Related Info

- One example for reading from a bucket via HTML can be found here: https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/maintenance/oncall.html
- Parent issue that this is part of #1 

# Discussion
Slack thread: https://kubernetes.slack.com/archives/C01CUSVMHPY/p1642720739011300

/sig testing k8s-infra security

**Comment by sftim** [comment]
I guess also
/sig security

**Comment by nehaLohia27** [comment]
cc @rajaskakodkar

**Comment by PushkarJ** [comment]
Duplicated by #32 and the PRs that fixed it
/close
