### ISSUE TITLE
Create .gitignore file

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#36]
As with all repos, a `.gitignore` file helps with ensuring unneeded files are not accidentally added under git version control. We need one for k/sig-security repo that may look something like this at the root of the repo. 

```
# OSX leaves these everywhere on SMB shares
._*

# OSX trash
.DS_Store

# Eclipse files
.classpath
.project
.settings/**

# Files generated by JetBrains IDEs, e.g. IntelliJ IDEA
.idea/
*.iml

# Vscode files
.vscode

# Emacs save files
*~
\#*\#
.\#*

# Vim-related files
[._]*.s[a-w][a-z]
[._]s[a-w][a-z]
*.un~
Session.vim
.netrwhist

# User cluster configs
.kubeconfig
```

Example for a `.gitignore` file on k/k repo: https://github.com/kubernetes/kubernetes/blob/master/.gitignore

/sig security 
/help-wanted
/good-first-issue

**Comment by ShivamTyagi12345** [comment]
/triage-accepted
👍🏽
