### ISSUE TITLE
Kubernetes API Server Bypass Risks

### ISSUE THREAD

**Issue by raesene** [kubernetes/sig-security#42]
Based on a suggestion from @JimBugwadia on [slack](https://kubernetes.slack.com/archives/C8P1DRTJA/p1646415935134399?thread_ts=1646351143.746869&cid=C8P1DRTJA) an idea for a good page on the Kubernetes website would be to collate configurations or privileges which could allow a malicious user or attacker to bypass the API server. As many key security controls (e.g. Auditing and admission control) are handled at the API server layer, attacks which bypass it can present a serious risk to cluster security.

Some examples :-

- [node/proxy](https://www.container-security.site/security_research/node_proxy.html) rights at the cluster level can allow users to directly communicate with the kubelet API, bypassing the API server.
- To an extent users being able to create static pods bypasses some API server controls
- Direct access to the etcd database will effectively allow attackers to retrieve things like secrets without that access being visible in API server audit logs.

/sig security docs

**Comment by raesene** [comment]
I've put some initial thoughts for this in a hackmd [here](https://hackmd.io/@raesene/r1FdqwKj5/edit) feel free to add/suggest changes :)

Once we've gathered some ideas, we can create a PR for k/website to get wider feedback

**Comment by p4ck3t0** [comment]
What is about the pause container? An attacker who can change the pause container image, also bypasses the API? :thinking: 
Is that something we could add to that list?

**Comment by raesene** [comment]
@p4ck3t0 so at the moment we're focusing more on how things are changed rather than what they'd change, but you raise a good point, in that people could modify container images either on-host or via the CRI daemon, and that's definitely worth including.

**Comment by raesene** [comment]
This has been merged now woooo https://github.com/kubernetes/website/pull/35908
