### ISSUE TITLE
Document previous learning sessions in SIG Security Tooling

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#43]
## Description

- Create a markdown table that lists all the learning sesions here: https://www.youtube.com/playlist?list=PLrQN4xC6U5D9I0LGJxZuXbfvi1qwPqcim to celebrate past presenters and encourage new speakers!

- Please note some of these are working session and some are learning sessions. For more context, refer the meeting minutes page: https://docs.google.com/document/d/1_Rn7S8UPMtXdu6EDl4_L2Ogb433z7hlxPs7El8TfNNg/edit

- The markdown file `learning-sessions.md` can exist under this directory https://github.com/kubernetes/sig-security/tree/main/sig-security-tooling

### Pre-requisites

Somebody working on this would need:
- Basic markdown skills or desire to learn them
- Become a member of https://groups.google.com/g/kubernetes-sig-security to access the meeting minutes

### Format

| date | topic | speaker | link |
| -----|-------- | ------|------- |
| 02-21-2022 | Learning session template | Goose geese | youtube.url 

/sig security
/kind cleanup

**Comment by chetak123** [comment]
Hey @mhammadsaani I am working on this issue (actually I was AFK for few days due to some personal work), and I will be making PR soon.

**Comment by cailynse** [comment]
@chetak123 - is this issue closed by #47 ?
