### ISSUE TITLE
REQUEST: Learning sessions on Eraser

### ISSUE THREAD

**Issue by salaxander** [kubernetes/sig-security#49]
**Please tell us a bit more about the topic** 
We would like to demo and get feedback on an open source project we've been working on to cleanup stale and vulnerable images on Kubernetes clusters -> https://github.com/Azure/eraser

**Please share speaker details**
@salaxander - available to present at the 6/30 or 7/14 meetings

**Explain the benefits to the community that this session provides**
The community could hopefully benefit from the project, I've spoken to a lot of folks that have struggled with the problem this project aims to solve. We're also very interested in moving the project out of the Azure org to support more openness.

**Comment by PushkarJ** [comment]
Thank you @salaxander would you be open to presenting this on July 5th SIG Security Tooling meeting (8:30 AM Pacific) ? The meeting dates you mentioned are for the SIG meetings whereas learning sessions are part of tooling sub-project which has its own meeting schedule

**Comment by salaxander** [comment]
@PushkarJ That would be perfect!

**Comment by salaxander** [comment]
Thanks for helping us get this setup @PushkarJ! Closing as the session has been completed
