### ISSUE TITLE
Blog post on PSP history context

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/sig-security#51]
Ref: https://kubernetes.slack.com/archives/C019LFTGNQ3/p1653483955189929

/assign @mtardy

**Comment by mtardy** [comment]
We had a discussion about that in the `#release-comms` channel on the Kubernetes Slack that can be found [here](https://kubernetes.slack.com/archives/CNT9Y603D/p1658737351321419). The tl;dr is that a dedicated article could be interesting and that it could be published around Kubernetes v1.25 release, a few days after or a few weeks after!

Here is a link to an early draft of what it could be https://hackmd.io/@mtardy/S1cQSCJCc/edit.

**Comment by mtardy** [comment]
The blogpost is out: https://kubernetes.io/blog/2022/08/23/podsecuritypolicy-the-historical-context/ 🥳!

/close
