### ISSUE TITLE
REQUEST: Request a Learning session on Trousseau

### ISSUE THREAD

**Issue by romdalf** [kubernetes/sig-security#54]
**Please tell us a bit more about the topic** 
Following the CNCF Sandbox Inclusion Meeting feedback, we would like to share with you an overview of why, what, and how [Trousseau](https://github.com/ondat/trousseau) addresses the Secret Management using the Kubernetes KMS provider plugin constructs. 
This session will be a walkthrough demo about the design, current status, roadmap and getting the SIG Security advice to nurture the Trousseau project. 

**Please share speaker details**

@romdalf 

**If speaker is confirmed, please share speaker availability** 

The SIG Security Tooling time slot at 8.30AM PDT is perfect. 
Just confirm the date. 

**Explain the benefits to the community that this session provides**

The community will gain awareness on the benefit from such open source tool that bridges the native Kubernetes Secret Management (or any resources with sensitive data like a ConfMap) and the usage of one or multiple external KMS provider(s) while keeping the data locally within the cluster in etcd. 
This session will also expose our vision about the next steps about the KMS provider pluging support from both the Kubernetes and Trousseau perspectives.

**Comment by PushkarJ** [comment]
Thank you for submitting this!! @romdalf I see you are doing a presentation with CNCF TAG Security too: https://github.com/cncf/tag-security/issues/963

Would you like to host this session before or after the TAG Security presentation?

**Comment by romdalf** [comment]
Hi @PushkarJ - happy to do it before if there is a convenient time slot to do so.

**Comment by PushkarJ** [comment]
@romdalf we have #53 scheduled for Aug 16. So next date would be Sep 6 if that works for you. 

I will let you know in case we can do it earlier but if not please leave a comment here as a reminder, end of August so I can start the background work to schedule this for Sept 6 :)

**Comment by romdalf** [comment]
Thank you! September 6th is perfect and will comment as requested.

**Comment by PushkarJ** [comment]
Hi @romdalf since September 6 morning slot is right after a long weekend in the US, I am proposing to move the learning session to Sept 20 instead. Do you have any concerns with that?

**Comment by romdalf** [comment]
Sounds good to me, It's a go from my side!

**Comment by PushkarJ** [comment]
@romdalf are you still on for Sept 20 8:30 AM to 9:15 AM PDT timeslot?
