### ISSUE TITLE
[Blog post] Current State of findings from Kubernetes Third Party Security Audit of 2019

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#56]
## Description
Write a blog post as pre-cursor to publication of third party security of audit 2021/22 that describes the current state of findings from the audit of 2019 

## Motivation
As we prepare for #13 it is useful, to take a look back current state of Third Party Security audit of 2019. This issue attempted to keep track of status of findings reported https://github.com/kubernetes/kubernetes/issues/81146 . The blog post will attempt to dive deeper into this and become a point in time summary of the current state of the findings reported from 2019.

This will help folks gain confidence through transparent communication of work done by community to address the findings and bubble up any findings that need help from community contributors 

/cc @reylejano 
/sig security docs
/area security blog
/wg security-audit

**Comment by cailynse** [comment]
I'm interested in working on this, but would likely need a bit of assistance.

**Comment by PushkarJ** [comment]
Awesome @cailynse Let me share a draft with you in next couple of weeks with placeholders where you could contribute :)

**Comment by sftim** [comment]
I'm an editor for the Kubernetes blog, and I can help introduce folks to other people from the blog editorial side.
