### ISSUE TITLE
Create a list of alert-worthy events for Kubernetes

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#6]
Action item from https://github.com/kubernetes/website/pull/29791/files#r715134850
> Can SIG Security recommend a good sample / baseline alert events that we use in all examples moving forward? 

/sig security docs
/kind feature

**Comment by savitharaghunathan** [comment]
@PushkarJ I am not able to find more context on this. If you get sometime can you add some context? Thanks :)
