### ISSUE TITLE
SIG-Security-Docs idea - Risks of hostPath volumes

### ISSUE THREAD

**Issue by raesene** [kubernetes/sig-security#62]
This came up on the API Server bypass page discussions and also in a [slack thread](https://kubernetes.slack.com/archives/C8P1DRTJA/p1661905584043699) that there's some fuzziness about what *exactly* the risks of `hostPath` volumes are, and how easy it would be to break out in various scenarios.

It'd be a nice page to have to bottom out this risk and provide some guidance for cluster operators on where it's more/less safe to use `hostPath` volumes.

**Comment by mtardy** [comment]
Big +1 on this one.

Shameless plug but the discussion on slack started from the person bringing this topic maybe being a bit "scared" about hostpaths after reading [this small article](https://blog.quarkslab.com/kubernetes-and-hostpath-a-love-hate-relationship.html) I wrote about the various hostpath vulnerabilities and seeing [the big red warning in the volume doc](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath).

For the tl;dr of the discussion, in my understanding, they needed to have a disk to write to with a high I/O bandwidth but did not want to expose their cluster to vulnerability or insecure settings by creating/allowing hostpaths.

So I think a page of specialized documentation on the risk of host file system exposure, "what's safe, what's not safe, what are the attack scenarios through that", could be very valuable for people who want to have a secure cluster while ensuring usability for their users.

**Comment by sftim** [comment]
How about an [evergreen](https://github.com/kubernetes/website/pull/31934) blog article on the topic?

**Comment by raesene** [comment]
Some initial brainstorming notes for this one. please expand / edit etc :)

https://hackmd.io/@raesene/BJ9eTy--s/edit

(cc @mtardy )

@sftim Are you thinking blog + docs page, or just a blog?

**Comment by sftim** [comment]
Just a blog article - if it's evergreen, we can add lots of inbound links from other pages.

Here's an example of an evergreen article that works well and gets referenced: https://kubernetes.io/blog/2020/09/03/warnings/
