### ISSUE TITLE
CVE Feed: Include a timestamp field for each CVE indicating when it was last updated

### ISSUE THREAD

**Issue by Dentrax** [kubernetes/sig-security#63]
**This is a Feature Request**

`-`

**What would you like to be added**

https://kubernetes.io/docs/reference/issues-security/official-cve-feed/index.json

* Add `lastUpdateTime` timestamp field in the root.
* Add `timestamp` field to CVE entry

**Why is this needed**

In the current response, there is no `lastUpdateTime` field. So it's challenging to distinguish when the CVE Feed is actually updated or it's already up-to-date.

I think `timestamp` field is also necessary to indicate when the CVE is added to the feed. There could be a time-window between _CVE discover time_ versus _CVE added to feed time_.

**Alternative Solution:**

Use [RSS 2.0 standard](https://validator.w3.org/feed/docs/rss2.html) instead for better scaling for further requirement needs.

**Comments**
`-`

cc @developer-guy

**Comment by sftim** [comment]
Once the upstream feed has this data, we may also want changes to [k/website](https://github.com/kubernetes/website/) to make that last updated information available.

For example, we could calculate an overall last-updated for the whole feed, and put that onto https://kubernetes.io/docs/reference/issues-security/official-cve-feed/ as text.

**Comment by PushkarJ** [comment]
/retitle CVE Feed: Include a timestamp field for each CVE indicating when it was last updated

(Dividing the scope between this issue and #73 and #72)

**Comment by mtardy** [comment]
This would be trivial to implement after this one is merged https://github.com/kubernetes/sig-security/pull/75.
I could do it quickly!
/assign

**Comment by mtardy** [comment]
I just added a commit to fix this in https://github.com/kubernetes/sig-security/pull/75#issuecomment-1359109214.

**Comment by PushkarJ** [comment]
Fixed by #76 via _date_published_ field. Feel free to re-open if you think this needs more work to be resolved. 

/close
