### ISSUE TITLE
Kubernetes Admission Control Threat Model

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/sig-security#7]
Rory McCune is working on a threat model for K8s admission control. 
For now, creating this tracking issue. More details will be updated soon.

cc: @raesene 

/sig security docs

**Comment by raesene** [comment]
Current draft is open for comments/additions/corrections - https://docs.google.com/document/d/1tQTZ6wrD2udbUGL7xhc3SRxqyTvS8FQUlL59KHYHcY8/edit?usp=sharing

**Comment by raesene** [comment]
D'ya think we can close this one now?

**Comment by savitharaghunathan** [comment]
Thanks, Rory. 
/close
