### ISSUE TITLE
CVE Feed: Add Prow job link as a metadata field

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#71]
## Description

Freshness of a feed is dependent on successful scheduled prow job runs. Adding a link to job in the "json" feed and the markdown description, allows folks to look at the prow job to ensure that prow job has been running successfully as recent as few hours ago.

## Details

Add a field named "prow job", under the custom map of `_kubernetes.io` at the top of the feed (not part of each CVE item) with single value being "https://testgrid.k8s.io/sig-security-cve-feed#auto-refreshing-official-cve-feed"

**Comment by mtardy** [comment]
> Add a field named "prow job", under the custom map of `_kubernetes.io` at the top of the feed (not part of each CVE item) with single value being "https://testgrid.k8s.io/sig-security-cve-feed#auto-refreshing-official-cve-feed"

Ah I was thinking that we wanted to link to the specific job that created the created the yaml itself, and I'm not sure we can do that simply. If it's a just an hardcoded single value to the testgrid.k8s.io website, I guess it's fairly trivial! :)

/assign
