### ISSUE TITLE
CVE Feed: Add `lastUpdatedAt` as a metadata field

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#72]
## Description

Freshness of a feed is important to the end users to have guarantees on when it was last updated. Adding a field which tells you whenever the feed was last updated is good step in that direction.

## Details

JSON: Add a field named "lastUpdatedAt", under the custom map of `_kubernetes.io` at the top of the feed (not part of each CVE item) with single value being "<UnixTimeStamp>"

Markdown: Add a line explaining mentioning when the feed was last updated with a link to unix time to local timezone converter

**Comment by mtardy** [comment]
I think it would be trivial if the JSON script was actually creating the whole object and not just the subpart in `items`. So it would require modification on the k/website part. See here https://github.com/kubernetes/sig-security/pull/75#issuecomment-1357830915.
