### ISSUE TITLE
REQUEST: Request a Learning session for Copa

### ISSUE THREAD

**Issue by salaxander** [kubernetes/sig-security#79]
**Please tell us a bit more about the topic** 
Copacetic ([https://github.com/project-copacetic/copacetic](https://github.com/project-copacetic/copacetic)) is a recently released open source tool to handle container patching based on vulnerability data obtained from a scanner (Trivy is currently supported). We'd like to share a little bit about the project and get some feedback from the community on the approach and features.

Note: Not a vendor pitch, there is no commercial offering associated with Copa.

**Please share speaker details**
Xander Grzywinski (GitHub: [@salaxander](https://github.com/salaxander) / K8s Slack: `@Xander`)

**If speaker is confirmed, please share speaker availability** 
Available for any of the upcoming SIG security tooling community meeting times

**Explain the benefits to the community that this session provides**
We're hoping that the communtiy will get the chance to try out a new tool in the ecosystem that will potentially make their workflows a little easier.

**Comment by salaxander** [comment]
@PushkarJ - Any update on this you're able to share? Thanks!!

**Comment by PushkarJ** [comment]
Thanks for the ping @salaxander 

How does the March 29 or April 12 sound like for the team? We meet at 8AM Pacific time zone. 

(I need to update the template to reflect new time slot)

**Comment by salaxander** [comment]
@sozercan @ashnamehrota - Do you have a preference for either of those dates?

**Comment by salaxander** [comment]
@PushkarJ - let's do March 29 since April 12 bumps us right up against KubeCon. Also 1.27 releases on April 11 so I'm expecting folks will be super busy right around then.

Thanks!!

**Comment by PushkarJ** [comment]
Ok let's do March 29 ✅
