### ISSUE TITLE
Cluster-API Security Self-Assessment Initiative

### ISSUE THREAD

**Issue by rficcaglia** [kubernetes/sig-security#8]
This is to consolidate info and inform all the interested folks regarding discussions around security assessment of cluster-api sub-project.

This is our first attempt as a community where a Security SIG will perform a security assessment of a sub-project of a graduated CNCF project. So we expect to make slow but reasonable progress and will be open for feedback on how we can improve for the benefit of others who will follow us.

The first step of a (community driven) security assessment of a project is a self-assessment of the project. Although, this is typical done by the project maintainers, some of us in #sig-security  would be happy to take a first crack at filling out the outline template provided by CNCF TAG-Security.

Currently the volunteers are educating themselves on cluster-api docs and presentations and will coordinate with maintainers (who understandably are very busy but are engaged).

Related items:

https://github.com/kubernetes/community/pull/5792

https://github.com/cncf/tag-security/issues/603

https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/Fi0UGzfbQfY

**Comment by PushkarJ** [comment]
Just wanted to leave some updates here for folks who stumble upon this and are wondering what's the current status:

- The group collaborates and meets regularly on [tag-security-assess-capi](https://kubernetes.slack.com/archives/C022K4F2W4W)
- The scope is limited to Cluster API AWS provider focussing on two flows: workload control plane node creation and workload control plane node worker node creation
- We conducted data flow diagram exercises across several different meetings in the past few months on these flows
- The data flows along with identified threats are being discussed at the time of writing this update
- We expect that the outcome of the discussion would be a list of Github issues that will enable us to address any identified threats in Cluster API

/assign @rficcaglia @PushkarJ 
/sig cluster-lifecycle security

**Comment by PushkarJ** [comment]
So far as a follow up on the security assessment, the following issues have been created:

- [cluster-api/issues/6153](https://github.com/kubernetes-sigs/cluster-api/issues/6153) 
- [cluster-api/issues/6329](https://github.com/kubernetes-sigs/cluster-api/issues/6329) 
- [cluster-api/issues/6152](https://github.com/kubernetes-sigs/cluster-api/issues/6152) 
- [cluster-api/issues/6151](https://github.com/kubernetes-sigs/cluster-api/issues/6151)

**Comment by PushkarJ** [comment]
Project tracker to manage completion of identified issues can be found here: https://github.com/orgs/kubernetes/projects/83/views/1
