### ISSUE TITLE
Bug: Unbound variable in vulnerability scanning script

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#85]
Job run: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-snyk-master/1643706990876168192/build-log.txt

```
/bin/bash: line 30: null: unbound variable
```

Fix needs to happen where `TOTAL_COUNT` variable is set as `null` when curl command returns this error:

```
{"message":"API rate limit exceeded for 98.37.153.210. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

We need to check if the variable is "null" and then fail the job if it is since that means we are unable to filter out vulnerabilities that we can.

Something like this would work (optional improvements for redundant code are welcome too):

```
                  if [ $TOTAL_COUNT == "null" ]; then
                      echo "Vulnerability filtering failed"
                      exit 1
                  else
                    if [[ $TOTAL_COUNT -eq 0 ]]; then
                      echo "Vulnerability filtering failed"
                      exit 1
                    fi
                  fi
```

/sig security testing k8s-infra
/kind bug

**Comment by PushkarJ** [comment]
@carlory hope you're well. Are you still working on this or need any help from me?

**Comment by carlory** [comment]
Sorry for the delay. I'll do it this week.

**Comment by PushkarJ** [comment]
The chances of this recurring are greatly reduced thanks to https://github.com/kubernetes/test-infra/pull/31076

**Comment by PushkarJ** [comment]
Since there have been no newer failures because of this bug, it seems this would be okay to close for now. If anyone still wants to work on this, please open a PR with a fix and reopen this issue again so that it is resolved by the PR.
