### ISSUE TITLE
REQUEST: Request a Learning session on bpfd

### ISSUE THREAD

**Issue by anfredette** [kubernetes/sig-security#91]
**Please tell us a bit more about the topic** 

[bpfd](https://bpfd.dev/) is a relatively new open-source project which provides a system daemon aimed at simplifying the deployment and management of eBPF programs. Its goal is to enhance the developer experience as well as provide features to improve security, visibility, and program cooperation. bpfd includes a Kubernetes operator to bring those same features to Kubernetes, allowing users to safely deploy eBPF via custom resources across nodes in a cluster.

**Please share speaker details**

Andre Fredette is a software engineer on the networking team in the Office of the CTO at Red Hat.  He is also a maintainer for the bpfd project.

github: anfredette
k8s slack: Andre Fredette

**If speaker is confirmed, please share speaker availability** 

We’d like to present during one of the regular SIG Security Tooling meetings after 6/16/23.  6/21/23 would be great.

**Explain the benefits to the community that this session provides**

eBPF is a powerful tool that can be used for many purposes including networking, monitoring, tracing, and security.  Because of this, Kubernetes applications that use eBPF are proliferating.  However, eBPF also poses security risks because applications using eBPF require increased permission levels including at least CAP_BPF.

We believe that the SIG Security community would benefit from learning about bpfd because it will both facilitate the development of security-related applications as well as help mitigate the security risks when eBPF applications are used in a Kubernetes environment.

Please check out the bpfd website ([bpfd.dev](https://bpfd.dev/)) if you want to learn more.

**Comment by PushkarJ** [comment]
Thank you @anfredette for submitting this request. We have one more request that is pending. I will check if they can do June 21. If not, the spot is yours.

**Comment by anfredette** [comment]
Thanks!

**Comment by PushkarJ** [comment]
You are on for bpfd on June 21. Does that time slot still work for you @anfredette ?

**Comment by PushkarJ** [comment]
Cool. 45 mins in total. You can divide between Q&A, demos, presentations, however you like :) Look forward to seeing you on Wed, June 21 8AM pacific

**Comment by anfredette** [comment]
Sounds good.

**Comment by PushkarJ** [comment]
@tabbysable can you please add a link to June 21 2023 Tooling session as a comment?

/remove-lifecycle stale

**Comment by anfredette** [comment]
We had this learning session on 6/21/2023, so this issue can be closed.  Thanks, Andre
