### ISSUE TITLE
Kubernetes Policy-Based Governance, Risk, and Compliance paper

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes/sig-security#93]
The Policy WG has drafted a paper on Kubernetes GRC:

https://docs.google.com/document/d/1pWFBfMloSgupjJBcyq45qg9UHkaPjfAyUQHgmBdTqgQ/edit

This issues is to track the migration to markdown. This is WIP at:

https://github.com/JimBugwadia/sig-security/blob/policy_grc_paper/sig-security-docs/papers/policy_grc/kubernetes-grc.md

**Pending Tasks:**
- [x] add links
- [x] add diagrams
- [x] add reviewer affiliations

**Comment by sunstonesecure-robert** [comment]
is there a format for diagrams we need to use? (or prefer to use)

**Comment by JimBugwadia** [comment]
> is there a format for diagrams we need to use? (or prefer to use)

Typically PNG.
